[project]
name = "datasets"
version = "0.1.0"
description = "Python package to automatically download impulse response datasets."
readme = "README.md"
authors = [
    { name = "Art Pelling", email = "a.pelling@tu-berlin.de" }
]
requires-python = ">=3.13"
dependencies = [
    "pooch @ git+https://github.com/artpelling/pooch.git@dpsace-doi-downloader",
    "pyfar>=0.7.3",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.uv.sources]
pooch = { git = "https://github.com/artpelling/pooch.git", rev = "dspace-doi-downloader" }
